#!/bin/bash
set -euo pipefail

UTILS_PATH="./modules/utils.sh"
if [ ! -f "$UTILS_PATH" ] && [ -n "${BASH_SOURCE[0]:-}" ]; then
    UTILS_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/utils.sh"
fi
# shellcheck source=/dev/null
[ -f "$UTILS_PATH" ] && source "$UTILS_PATH"

: "${RED:=$'\033[0;31m'}"
: "${GREEN:=$'\033[0;32m'}"
: "${YELLOW:=$'\033[1;33m'}"
: "${BLUE:=$'\033[0;34m'}"
: "${CYAN:=$'\033[0;36m'}"
: "${NC:=$'\033[0m'}"

declare -A CONFIGURE_ZSH_TEXT_EN=(
    ["config_title"]="Configuring Zsh (.zshrc)..."
    ["zsh_missing"]="Zsh is not installed. Please install Zsh first."
    ["backup_info"]="Existing .zshrc backed up to .zshrc.backup"
    ["config_success"]="Zsh configuration completed successfully!"
    ["plugins_info"]="Available plugins: zsh-autosuggestions, zsh-syntax-highlighting, zsh-completions"
    ["theme_info"]="Available themes: powerlevel10k"
    ["reload_info"]="Run 'source ~/.zshrc' or restart terminal to apply changes"
    ["config_done"]="Zsh configuration completed!"
)

declare -A CONFIGURE_ZSH_TEXT_TR=(
    ["config_title"]="Zsh (.zshrc) yapılandırılıyor..."
    ["zsh_missing"]="Zsh kurulu değil. Lütfen önce Zsh kurun."
    ["backup_info"]="Mevcut .zshrc dosyası .zshrc.backup olarak yedeklendi"
    ["config_success"]="Zsh yapılandırması başarıyla tamamlandı!"
    ["plugins_info"]="Mevcut eklentiler: zsh-autosuggestions, zsh-syntax-highlighting, zsh-completions"
    ["theme_info"]="Mevcut temalar: powerlevel10k"
    ["reload_info"]="Değişiklikleri uygulamak için 'source ~/.zshrc' çalıştırın veya terminali yeniden başlatın"
    ["config_done"]="Zsh yapılandırması tamamlandı!"
)

configure_zsh_text() {
    local key="$1"
    local default_value="${CONFIGURE_ZSH_TEXT_EN[$key]:-$key}"
    if [ "${LANGUAGE:-en}" = "tr" ]; then
        printf "%s" "${CONFIGURE_ZSH_TEXT_TR[$key]:-$default_value}"
    else
        printf "%s" "$default_value"
    fi
}

configure_zsh() {
    echo -e "\n${BLUE}╔═══════════════════════════════════════════════╗${NC}"
    echo -e "${YELLOW}${INFO_TAG}${NC} $(configure_zsh_text config_title)"
    echo -e "${BLUE}╚═══════════════════════════════════════════════╝${NC}"
    
    # Check if zsh is installed
    if ! command -v zsh >/dev/null 2>&1; then
        echo -e "${RED}${ERROR_TAG}${NC} $(configure_zsh_text zsh_missing)"
        return 1
    fi

    local zshrc_file="$HOME/.zshrc"
    local backup_file="$HOME/.zshrc.backup"

    # Backup existing .zshrc if it exists and no backup exists
    if [ -f "$zshrc_file" ] && [ ! -f "$backup_file" ]; then
        cp "$zshrc_file" "$backup_file"
        echo -e "${YELLOW}${INFO_TAG}${NC} $(configure_zsh_text backup_info)"
    fi

    # Detect available plugins and themes
    local custom_plugins_dir="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins"
    local custom_themes_dir="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes"
    
    local available_plugins=()
    local available_themes=()

    # Check for available plugins
    [ -d "$custom_plugins_dir/zsh-autosuggestions" ] && available_plugins+=("zsh-autosuggestions")
    [ -d "$custom_plugins_dir/zsh-syntax-highlighting" ] && available_plugins+=("zsh-syntax-highlighting")
    [ -d "$custom_plugins_dir/zsh-completions" ] && available_plugins+=("zsh-completions")

    # Check for available themes
    [ -d "$custom_themes_dir/powerlevel10k" ] && available_themes+=("powerlevel10k")

    # Create optimized .zshrc
    echo -e "${YELLOW}${INFO_TAG}${NC} Creating optimized ~/.zshrc configuration..."
    
    cat > "$zshrc_file" << 'EOF'
# Zsh Configuration File
# Generated by Linux AI Setup Script

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load.
ZSH_THEME="powerlevel10k/powerlevel10k"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Change command execution time stamp format
HIST_STAMPS="yyyy-mm-dd"

# Which plugins would you like to load?
plugins=(
EOF

    # Add available plugins to the plugins list
    for plugin in "${available_plugins[@]}"; do
        echo "  $plugin" >> "$zshrc_file"
    done

    cat >> "$zshrc_file" << 'EOF'
)

# Source Oh My Zsh
if [ -f "$ZSH/oh-my-zsh.sh" ]; then
    source "$ZSH/oh-my-zsh.sh"
fi

# User configuration
export EDITOR='nano'
export LANG=en_US.UTF-8

# Zsh Syntax Highlighting (if installed)
if [ -f "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]; then
    source "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

# Zsh Completions configuration
if [ -d "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/plugins/zsh-completions" ]; then
    autoload -U compinit
    compinit -i
fi

# Custom aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
alias ..='cd ..'
alias ...='cd ../..'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Git aliases
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git pull'
alias gd='git diff'

# System update aliases
if command -v apt-get >/dev/null 2>&1; then
    alias update='sudo apt-get update && sudo apt-get upgrade -y'
elif command -v yum >/dev/null 2>&1; then
    alias update='sudo yum update -y'
elif command -v dnf >/dev/null 2>&1; then
    alias update='sudo dnf update -y'
elif command -v pacman >/dev/null 2>&1; then
    alias update='sudo pacman -Syu --noconfirm'
fi

# Powerlevel10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
EOF

    echo -e "${GREEN}${SUCCESS_TAG}${NC} $(configure_zsh_text config_success)"
    
    if [ ${#available_plugins[@]} -gt 0 ]; then
        echo -e "${YELLOW}${INFO_TAG}${NC} $(configure_zsh_text plugins_info): ${available_plugins[*]}"
    fi
    
    if [ ${#available_themes[@]} -gt 0 ]; then
        echo -e "${YELLOW}${INFO_TAG}${NC} $(configure_zsh_text theme_info): ${available_themes[*]}"
    fi
    
    echo -e "${YELLOW}${INFO_TAG}${NC} $(configure_zsh_text reload_info)"
    echo -e "${GREEN}${SUCCESS_TAG}${NC} $(configure_zsh_text config_done)"
}

main() {
    configure_zsh "$@"
}

main "$@"